tabscanner:
  api:
    key:
security:
  jwt:
    secret-key: 
spring:
  application:
    name: rachai-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/rachai_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
groq:
  api:
    key: 
