tabscanner:
  api:
    key:
security:
  jwt:
    secret-key: 9a4f632e22824707a72d7df7a36081ab23e595a81e374ff4820bc0a12e2764b8
spring:
  application:
    name: rachai-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: Dev@Spring2026!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/rachai_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
groq:
  api:
    key: 
