server.port=8081
# Nome da aplicação
spring.application.name=rachai-api

# Configuração do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:rachaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que o Spring crie as tabelas sozinho com base nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do banco no navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
